version: '2'

networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:latest'
    container_name: redis
    ports:
      - 6379:6379
    environment:
      # - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=6379
      - REDIS_PASSWORD=123